### ISSUE TITLE
Node v12 Syntactic sugar imcompatibility

### ISSUE THREAD

**Issue by ziopod** [vuetter/vite-plugin-vue-svg#1]
Syntactic sugar for chaining operator `?.` are not compatible with old version of Nodejs. This create issue with some services like Forestry.io 

I have this error with Forestry.io  live server (runnig under Nodejs v.12):

~~~
failed to load config from /srv/vite.config.js
error when starting dev server:
/srv/node_modules/@vuetter/vite-plugin-vue-svg/dist/index.js:12
        const attrs = options?.htmlWrapper?.attrs ?? {};
                              ^

SyntaxError: Unexpected token '.'
~~~

The optionnal chaining operator `?.` cause issue with Nodejs v.12

For example, this line of instruction can be replaced by :

~~~
const attrs = options.htmlWrapper ? options.htmlWrapper.attrs  : {};
~~~

This is less sleek, but more robust (And we can use it on services that are struggling to update).

P.S.: On my side, I have notified Forestry to update their service.

**Comment by Eseath** [comment]
Fixed in version 0.1.2
